"""Basilisk downstream client adapter.

This namespace owns Basilisk-specific strategy construction and strategy-aware
compilation. The generic Compiler package remains strategy-agnostic.
"""

from .compiler import compile_strategy_profile, compile_strategy_runtime_profile
from ...ir.civ_profile import ByzantineProfile, resolve_effective_civ
from ...ir.strategy import (
    CapabilityIntent,
    CapabilityIntentKind,
    CapabilityRecoveryContract,
    ExecutionDemandTemplate,
    OpportunityCostPolicy,
    PostureTransition,
    ProtectedResourceFloor,
    ResolvedStrategyProfile,
    StrategicBinding,
    StrategicCapabilityObservation,
    StrategicCapabilityObservationKind,
    StrategicDemandSpec,
    StrategicObservationSpec,
    StrategicEvidence,
    StrategicEvidenceKind,
    StrategicEvidenceSource,
    StrategicPriority,
    StrategicTarget,
    StrategicTargetKind,
    StrategyCompilation,
    StrategyEnvelope,
    StrategyPosture,
    StrategyProfile,
    build_byzantine_castle_strategy,
    build_land_castle_strategy,
    lower_strategy_profile,
    resolve_strategy_profile,
)
from ...ir.strategy_runtime import (
    EvidenceTruth,
    ObservationReferenceBinding,
    OpportunityCostRuntimeState,
    ReassessmentReason,
    RuntimeObservationSnapshot,
    StrategicDemandRuntimeState,
    StrategicEvidenceBinding,
    StrategicObservation,
    StrategicObservationType,
    StrategicPredicate,
    StrategyRuntimeState,
    bind_observation_reference,
    bind_strategic_capability_observation,
    bind_strategic_evidence,
    evaluate_binding,
    evaluate_strategy_runtime,
)

__all__ = (
    "ByzantineProfile",
    "resolve_effective_civ",
    "compile_strategy_profile",
    "compile_strategy_runtime_profile",
    "CapabilityIntent",
    "CapabilityIntentKind",
    "CapabilityRecoveryContract",
    "ExecutionDemandTemplate",
    "OpportunityCostPolicy",
    "PostureTransition",
    "ProtectedResourceFloor",
    "ResolvedStrategyProfile",
    "StrategicBinding",
    "StrategicCapabilityObservation",
    "StrategicCapabilityObservationKind",
    "StrategicDemandSpec",
    "StrategicObservationSpec",
    "StrategicEvidence",
    "StrategicEvidenceKind",
    "StrategicEvidenceSource",
    "StrategicPriority",
    "StrategicTarget",
    "StrategicTargetKind",
    "StrategyCompilation",
    "StrategyEnvelope",
    "StrategyPosture",
    "StrategyProfile",
    "build_byzantine_castle_strategy",
    "build_land_castle_strategy",
    "lower_strategy_profile",
    "resolve_strategy_profile",
    "EvidenceTruth",
    "ObservationReferenceBinding",
    "OpportunityCostRuntimeState",
    "ReassessmentReason",
    "RuntimeObservationSnapshot",
    "StrategicDemandRuntimeState",
    "StrategicEvidenceBinding",
    "StrategicObservation",
    "StrategicObservationType",
    "StrategicPredicate",
    "StrategyRuntimeState",
    "bind_observation_reference",
    "bind_strategic_capability_observation",
    "bind_strategic_evidence",
    "evaluate_binding",
    "evaluate_strategy_runtime",
)
