"""Machine audit of the generated Byzantine land capability surface."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from LearnerAI.Compiler.clients.basilisk import ByzantineProfile, build_byzantine_strategy
from LearnerAI.Compiler.ir.civ_profile import resolve_effective_civ


LAND_TARGETS = (
    ("Crossbow", "unit-line", "archer-line", "Castle ranged transition"),
    ("Arbalest", "technology", "arbalest", "Imperial ranged escalation"),
    ("Cavalier", "technology", "cavalier", "Imperial mounted escalation"),
    ("Hussar", "technology", "hussar", "Imperial low-gold mobility"),
    ("Onager", "technology", "onager", "Imperial ranged-mass siege escalation"),
    ("Siege Ram", "technology", "siege-ram", "Imperial building assault"),
    ("Trebuchet", "unit-line", "trebuchet-line", "Castle objective siege"),
    ("Bombard Cannon", "unit-line", "bombard-cannon-line", "Imperial precision siege"),
    ("Cataphract", "unit-line", "cataphract-line", "Byzantine Castle power"),
    ("Varangian Guard", "unit-line", "varangian-guard-line", "Infantry-pressure response"),
    ("Monk", "unit-line", "monk-line", "Castle conversion/relic support"),
)


def _slug(value: str) -> str:
    return value.lower().replace(" ", "-")


def capability_status(effective, kind: str, value: str) -> tuple[str, str]:
    try:
        if kind == "unit-line":
            line = effective.unit_line(value)
            if not line.members:
                return "OPEN", f"unit line {value} exists but has no verified members"
            statuses = tuple(
                effective.factual_status("unit", int(member)).value
                for member in line.members
            )
            if all(status == "VERIFIED" for status in statuses):
                return "VERIFIED", f"unit line {value} members are factually verified"
            return "PARTIAL", f"unit line {value} member statuses={statuses}"
        wanted = _slug(value)
        tech = next(tech for tech in effective.technologies if _slug(tech.name) == wanted)
        status = effective.factual_status("technology", int(tech.id)).value
        return status, f"technology {tech.name} id={int(tech.id)}"
    except (KeyError, StopIteration, ValueError):
        return "BLOCKED", f"verified game-data node for {kind}:{value} is unavailable"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("artifact")
    parser.add_argument("--report", required=True)
    args = parser.parse_args()

    artifact = Path(args.artifact).read_text(encoding="utf-8")
    effective = resolve_effective_civ(ByzantineProfile.for_update_185872())
    profile = build_byzantine_strategy(effective)
    demand_names = {demand.identity for demand in profile.demands}

    rows = []
    for label, kind, value, rationale in LAND_TARGETS:
        status, evidence = capability_status(effective, kind, value)
        needle = _slug(value)
        output_present = needle in artifact.lower()
        semantic_present = any(
            needle in demand.identity.lower()
            or needle in demand.execution.action.lower()
            or any(
                needle in execution.action.lower()
                for execution in demand.execution_demands
            )
            for demand in profile.demands
        )
        rows.append(
            {
                "capability": label,
                "game_data": status,
                "game_data_evidence": evidence,
                "strategy_demand_surface": semantic_present,
                "emitted_artifact": output_present,
                "rationale": rationale,
            }
        )

    report = {
        "artifact": str(args.artifact),
        "artifact_bytes": len(artifact.encode("utf-8")),
        "land_targets": rows,
        "release_candidate_states": {
            "strategic-primary-intent": "(goal strategic-primary-intent" in artifact,
            "counter-package": "counter-package-" in artifact,
        },
        "demand_count": len(demand_names),
    }
    Path(args.report).write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    for item in rows:
        print(
            f"{item['capability']}: game_data={item['game_data']} "
            f"strategy={item['strategy_demand_surface']} "
            f"artifact={item['emitted_artifact']}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
