"""Machine audit of generated Byzantine water, transport, and recovery coverage."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from LearnerAI.Compiler.clients.basilisk import ByzantineProfile, build_byzantine_strategy
from LearnerAI.Compiler.ir.civ_profile import resolve_effective_civ


UNIT_TARGETS = (
    ("Fishing Ship", 13, "fishing-ship-line"),
    ("Transport Ship", 545, "transport-ship-line"),
    ("Fire Galley", 1103, "fire-galley-line"),
    ("Fire Ship", 529, "fire-ship-line"),
    ("Fast Fire Ship", 532, "fire-ship-line"),
    ("Galley", 539, "galley-line"),
    ("War Galley", 21, "galley-line"),
    ("Galleon", 442, "galley-line"),
    ("Hulk", 2626, "hulk-line"),
    ("War Hulk", 2627, "hulk-line"),
    ("Carrack", 2628, "hulk-line"),
    ("Demolition Ship", 527, "demolition-raft-line"),
    ("Heavy Demolition Ship", 528, "demolition-raft-line"),
    ("Trade Cog", 17, "trade-cog-line"),
    ("Dromon", 1795, "dromon-line"),
)

WATER_DEMANDS = (
    "water-fishing-continuity",
    "water-transport-capability",
    "water-naval-defense",
    "water-naval-control",
)

WATER_RESEARCH = (
    "Fishing Lines",
    "Gillnets",
    "Warships",
    "Heavy Warships",
    "Fast Fire Ship",
    "Careening",
    "Dry Dock",
    "Greek Fire",
)

RECOVERY_TARGETS = (
    "water-fishing-continuity",
    "water-transport-capability",
    "water-naval-defense",
    "water-naval-control",
    "castle-commitment",
    "castle-second-town-center",
    "castle-stable-capability",
    "castle-siege-capability",
    "castle-monastery-capability",
    "imperial-university-capability",
    "adaptive-outpost",
)


def _slug(value: str) -> str:
    return value.lower().replace(" ", "-").replace("/", "-")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("artifact")
    parser.add_argument("--report", required=True)
    args = parser.parse_args()

    artifact = Path(args.artifact).read_text(encoding="utf-8").lower()
    effective = resolve_effective_civ(ByzantineProfile.for_update_185872())
    profile = build_byzantine_strategy(effective)
    demands = {demand.identity: demand for demand in profile.demands}

    units = []
    for label, unit_id, line_name in UNIT_TARGETS:
        unit = effective.unit(unit_id)
        units.append(
            {
                "capability": label,
                "unit_id": unit_id,
                "game_data": effective.factual_status("unit", unit_id).value,
                "line": line_name,
                "strategy": any(
                    line_name in demand.execution.action.lower()
                    or line_name in demand.identity.lower()
                    for demand in profile.demands
                ),
                "artifact": _slug(label) in artifact,
            }
        )

    researches = []
    for label in WATER_RESEARCH:
        found = [
            tech for tech in effective.technologies
            if _slug(tech.name) == _slug(label)
        ]
        if not found:
            researches.append(
                {"technology": label, "game_data": "BLOCKED", "strategy": False, "artifact": False}
            )
            continue
        tech = found[0]
        researches.append(
            {
                "technology": label,
                "game_data": effective.factual_status("technology", int(tech.id)).value,
                "strategy": any(
                    label.lower() in demand.identity.lower()
                    or _slug(label) in demand.execution.action.lower()
                    for demand in profile.demands
                ),
                "artifact": _slug(label) in artifact,
            }
        )

    water_demands = []
    for identity in WATER_DEMANDS:
        demand = demands[identity]
        water_demands.append(
            {
                "demand": identity,
                "required_primary_intent": (
                    demand.required_primary_intent.name
                    if demand.required_primary_intent is not None
                    else None
                ),
                "recovery_on_world_loss": demand.recovery_on_world_loss,
                "has_recovery_contract": demand.recovery.reopen_on_recovery,
                "artifact": identity.lower() in artifact,
            }
        )

    recovery = []
    for identity in RECOVERY_TARGETS:
        demand = demands.get(identity)
        recovery.append(
            {
                "demand": identity,
                "present": demand is not None,
                "recovery_on_world_loss": (
                    demand.recovery_on_world_loss if demand is not None else False
                ),
                "recovery_contract": (
                    demand.recovery.reopen_on_recovery if demand is not None else False
                ),
                "emitted_recovery_rule": (
                    f"Recovery: {identity}" in Path(args.artifact).read_text(encoding="utf-8")
                ),
            }
        )

    report = {
        "artifact_bytes": len(Path(args.artifact).read_bytes()),
        "strategic_primary_intent": "(goal strategic-primary-intent" in artifact,
        "units": units,
        "water_research": researches,
        "water_demands": water_demands,
        "recovery": recovery,
        "open_runtime_boundaries": [
            "transport landing completion witness",
            "exact dock placement heuristic",
            "naval target-selection causality",
            "fleet combat outcome simulation",
        ],
    }
    Path(args.report).write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    for row in units:
        print(
            f"{row['capability']}: game_data={row['game_data']} "
            f"strategy={row['strategy']} artifact={row['artifact']}"
        )
    for row in researches:
        print(
            f"research {row['technology']}: game_data={row['game_data']} "
            f"strategy={row['strategy']} artifact={row['artifact']}"
        )
    for row in water_demands:
        print(
            f"demand {row['demand']}: recovery={row['recovery_on_world_loss']} "
            f"contract={row['has_recovery_contract']} artifact={row['artifact']}"
        )
    for row in recovery:
        print(
            f"recovery {row['demand']}: present={row['present']} "
            f"world_loss={row['recovery_on_world_loss']} "
            f"emitted={row['emitted_recovery_rule']}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
