"""Deterministic semantic IR -> AoE2 .per emitter."""
from __future__ import annotations

from ..errors import CompileError
from ..ir import (
    ConstructionTransitionKind,
    NativeAttackLifecyclePlan,
    NativeControlPlan,
    NativeDucPlan,
    NativeEscrowReleasePlan,
    SemanticDemand,
)
from ..primitives import PrimitiveRegistry, default_de_registry
from ..runtime_binding import (
    BindingResult,
    GoalSlot,
    LifecycleEncoding,
    StrategicNumberSlot,
    TimerSlot,
)
from ..semantic.native_control import validate_native_control_plan
from ..semantic.construction import construction_transition_rules

MAX_RULES = 10_000
MAX_RULE_ELEMENTS = 32
MAX_LINE_LENGTH = 255
INITIALIZATION_CHUNK = 30


def _claim_name(conflict_class: str) -> str:
    return "action-claim-" + conflict_class.lower().replace("_", "-")


def _extract_rules(text: str) -> list[str]:
    rules = []
    cursor = 0
    while True:
        start = text.find("(defrule", cursor)
        if start < 0:
            return rules
        depth = 0
        end = None
        for index in range(start, len(text)):
            char = text[index]
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
                if depth == 0:
                    end = index + 1
                    break
        if end is None:
            raise CompileError("EMITTER-UNBALANCED-RULE: generated rule is not closed")
        rules.append(text[start:end])
        cursor = end


def _validate_artifact_budget(text: str) -> None:
    rules = _extract_rules(text)
    if len(rules) > MAX_RULES:
        raise CompileError(
            f"EMITTER-RULE-LIMIT: generated artifact has {len(rules)} rules; "
            f"DE limit is {MAX_RULES}"
        )
    longest_line = max((len(line) for line in text.splitlines()), default=0)
    if longest_line > MAX_LINE_LENGTH:
        raise CompileError(
            f"EMITTER-LINE-LIMIT: generated line has {longest_line} characters; "
            f"DE limit is {MAX_LINE_LENGTH}"
        )
    for index, rule in enumerate(rules, 1):
        elements = rule.count("(") - 1
        if elements > MAX_RULE_ELEMENTS:
            raise CompileError(
                f"EMITTER-RULE-ELEMENT-LIMIT: generated rule {index} has "
                f"{elements} elements; DE limit is {MAX_RULE_ELEMENTS}"
            )


def emit(
    demands: list[SemanticDemand],
    bindings: BindingResult,
    compiler_version: str = "0.4",
    *,
    registry: PrimitiveRegistry | None = None,
    control_plan: NativeControlPlan | None = None,
    duc_plan: NativeDucPlan | None = None,
    attack_plan: NativeAttackLifecyclePlan | None = None,
    escrow_plan: NativeEscrowReleasePlan | None = None,
) -> str:
    registry = registry or default_de_registry()
    if control_plan is not None:
        validate_native_control_plan(control_plan, registry)
    if duc_plan is not None:
        registry.validate_duc_plan(duc_plan)
    if attack_plan is not None:
        registry.validate_attack_plan(attack_plan)
    if escrow_plan is not None:
        registry.validate_escrow_release_plan(escrow_plan)
    out = [
        ";============================================================",
        "; AOE2 .PER GENERATED BY COMPILER",
        f"; Compiler: AoE2 .per Compiler {compiler_version}",
        "; Generated from validated semantic IR. Do not edit by hand.",
        ";============================================================",
        "",
        "; Demand goal constants",
    ]

    encoded: dict[str, LifecycleEncoding] = {}
    arbitration_requests = {}
    strategic_number_states = []
    timer_states = []

    for demand in demands:
        for state in demand.strategic_number_states:
            if any(
                existing_state.name == state.name
                for existing_state, _ in strategic_number_states
            ):
                raise CompileError(
                    f"EMITTER-SN-DUPLICATE: duplicate Strategic Number state '{state.name}'"
                )
            binding = bindings.binding_for(state.request.request_id)
            if binding.__class__.__name__ != "StrategicNumberSlot":
                raise CompileError(
                    f"EMITTER-SN-BINDING: state '{state.name}' has non-SN binding "
                    f"{type(binding).__name__}"
                )
            strategic_number_states.append((state, binding))

        for state in demand.timer_states:
            binding = bindings.binding_for(state.request.request_id)
            if not isinstance(binding, TimerSlot):
                raise CompileError(
                    f"EMITTER-TIMER-BINDING: state '{state.name}' has non-Timer binding "
                    f"{type(binding).__name__}"
                )
            if any(existing_state.name == state.name for existing_state, _ in timer_states):
                raise CompileError(
                    f"EMITTER-TIMER-DUPLICATE: duplicate Timer state '{state.name}'"
                )
            timer_states.append((state, binding))

    if timer_states:
        out.extend([
            "",
            "; Timer state constants",
        ])
        for state, binding in sorted(
            timer_states,
            key=lambda item: (
                item[0].request.request_id.owner.source_unit,
                item[0].request.request_id.owner.local_name,
                item[0].request.request_id.purpose,
            ),
        ):
            out.append(f"(defconst {state.name} {binding.id})")

        out.extend([
            "",
            "; Timer state initialization",
        ])
        for start in range(0, len(timer_states), INITIALIZATION_CHUNK):
            chunk = timer_states[start : start + INITIALIZATION_CHUNK]
            out += ["(defrule", "    (true)", "=>"]
            for state, _binding in chunk:
                if state.request.initialization_policy != "DISABLE_BEFORE_FIRST_USE":
                    raise CompileError(
                        f"EMITTER-TIMER-INIT-POLICY: unsupported initialization policy "
                        f"'{state.request.initialization_policy}' for timer '{state.name}'"
                    )
                out.append(f"    (disable-timer {state.name})")
            out.extend(["    (disable-self)", ")", ""])

    for state, binding in sorted(
        strategic_number_states,
        key=lambda item: (
            item[0].request.request_id.owner.source_unit,
            item[0].request.request_id.owner.local_name,
            item[0].request.request_id.purpose,
        ),
    ):
        out.append(f"(defconst {state.name} {binding.id})")

    if strategic_number_states:
        out.extend([
            "",
            "; Strategic Number state initialization",
        ])
        for start in range(0, len(strategic_number_states), INITIALIZATION_CHUNK):
            chunk = strategic_number_states[start : start + INITIALIZATION_CHUNK]
            out += ["(defrule", "    (true)", "=>"]
            for state, _binding in chunk:
                out.append(
                    f"    (set-strategic-number {state.name} {state.initial_value})"
                )
            out.extend(["    (disable-self)", ")", ""])

    for demand in demands:
        slot = bindings.binding_for(demand.lifecycle.slot.request_id)
        lifecycle = LifecycleEncoding.for_goal_slot(slot)
        encoded[demand.name] = lifecycle

        native_pass_constraints = registry.pass_constraints_for(demand.action.expression.head)
        for constraint in native_pass_constraints:
            out.append(
                f"; NATIVE-PASS-CONSTRAINT {demand.action.expression.head} "
                f"maximum-successes={constraint.maximum_successes}"
            )
            if (
                constraint.maximum_successes == 1
                and demand.action.arbitration_request is None
            ):
                raise CompileError(
                    f"EMITTER-NATIVE-PASS-CONSTRAINT: action '{demand.action.expression.head}' "
                    "requires a transient arbitration owner for maximum-successes=1"
                )

        request = demand.action.arbitration_request
        if request is not None:
            arbitration_requests[request.request_id] = request

        out.append(f"(defconst demand-{demand.name} {slot.id.value})")
        out.append(f"(defconst issued-{demand.name} {lifecycle.issued.value})")
        out.append(f"(defconst pending-{demand.name} {lifecycle.pending.value})")
        out.append(f"(defconst complete-{demand.name} {lifecycle.complete.value})")
        if demand.invalidation is not None:
            out.append(
                f"(defconst cancelled-{demand.name} {lifecycle.cancelled.value})"
            )
        if demand.construction_retry_barrier is not None:
            barrier_slot = bindings.binding_for(
                demand.construction_retry_barrier.request_id
            )
            if not isinstance(barrier_slot, GoalSlot):
                raise CompileError(
                    f"CONSTRUCTION-BARRIER-BINDING: construction retry barrier for "
                    f"'{demand.name}' resolved to '{type(barrier_slot).__name__}', expected GoalSlot"
                )
            out.append(
                f"(defconst construction-retry-barrier-{demand.name} "
                f"{barrier_slot.id.value})"
            )

    for request_id, _request in sorted(
        arbitration_requests.items(),
        key=lambda item: (item[0].owner.source_unit, item[0].purpose),
    ):
        slot = bindings.binding_for(request_id)
        conflict_class = request_id.purpose.split(":", 1)[1]
        out.append(f"(defconst {_claim_name(conflict_class)} {slot.id.value})")

    out.append("")

    if duc_plan is not None and not duc_plan.empty:
        out.append("; Native DUC execution plan")
        for rule in duc_plan.rules:
            out.append(f"; Native DUC rule: {rule.identity}")
            out.append("(defrule")
            out.extend(f"    {fact.source}" for fact in rule.facts)
            out.append("=>")
            out.extend(f"    {action.source}" for action in rule.actions)
            out += [")", ""]

    if attack_plan is not None and not attack_plan.empty:
        out.append("; Native attack lifecycle plan")
        for rule in attack_plan.rules:
            out.append(f"; Native attack rule: {rule.identity}")
            out.append("(defrule")
            out.extend(f"    {fact.source}" for fact in rule.facts)
            out.append("=>")
            out.extend(f"    {action.source}" for action in rule.actions)
            out += [")", ""]

    if escrow_plan is not None and not escrow_plan.empty:
        out.append("; Native escrow release plan")
        current_rule_order = None
        for operation in escrow_plan.operations:
            if operation.rule_order != current_rule_order:
                if current_rule_order is not None:
                    out += [")", ""]
                current_rule_order = operation.rule_order
                out.append(
                    f"; Native escrow release rule: {current_rule_order}"
                )
                out += ["(defrule", "    (true)", "=>"]
            out.append(f"    (release-escrow {operation.resource})")
        if current_rule_order is not None:
            out += [")", ""]

    if control_plan is not None:
        out.append("; Native persistent control plane")
        emitted_symbols = {
            line.split()[1]
            for line in out
            if line.startswith("(defconst ") and len(line.split()) >= 3
        }
        for state in sorted(control_plan.states, key=lambda item: item.identifier):
            binding = bindings.binding_for(state.request.request_id)
            if isinstance(binding, GoalSlot):
                value = binding.id.value
            elif isinstance(binding, StrategicNumberSlot):
                value = binding.id
            elif isinstance(binding, TimerSlot):
                value = binding.id
            else:
                raise CompileError(
                    f"CONTROL-PLANE-BINDING: state '{state.identifier}' resolved to unsupported "
                    f"binding type '{type(binding).__name__}'"
                )
            if state.identifier in emitted_symbols:
                raise CompileError(
                    f"CONTROL-PLANE-SYMBOL: duplicate emitted defconst '{state.identifier}'"
                )
            emitted_symbols.add(state.identifier)
            out.append(f"(defconst {state.identifier} {value})")

        out.append("")
        for rule in control_plan.rules:
            out.append(f"; Native control rule: {rule.identity}")
            out.append("(defrule")
            out.extend(f"    {fact.source}" for fact in rule.facts)
            out.append("=>")
            out.extend(f"    {action.source}" for action in rule.actions)
            out += [")", ""]

    if arbitration_requests:
        out.append("; Per-pass transient action arbitration")
        for request_id, _request in sorted(
            arbitration_requests.items(),
            key=lambda item: (item[0].owner.source_unit, item[0].purpose),
        ):
            conflict_class = request_id.purpose.split(":", 1)[1]
            out += [
                "(defrule",
                "    (true)",
                "=>",
                f"    (set-goal {_claim_name(conflict_class)} 0)",
                ")",
                "",
            ]

    construction_barrier_demands = tuple(
        demand for demand in demands if demand.construction_retry_barrier is not None
    )
    if construction_barrier_demands:
        out.append("; Per-pass construction retry barriers")
        for demand in construction_barrier_demands:
            out += [
                "(defrule",
                "    (true)",
                "=>",
                f"    (set-goal construction-retry-barrier-{demand.name} 0)",
                ")",
                "",
            ]

    if demands:
        out.append("; Demand initialization")
        for start in range(0, len(demands), INITIALIZATION_CHUNK):
            chunk = demands[start : start + INITIALIZATION_CHUNK]
            out += ["(defrule", "    (true)", "=>"]
            for demand in chunk:
                out.append(
                    f"    (set-goal demand-{demand.name} "
                    f"{encoded[demand.name].active.value})"
                )
            out.append("    (disable-self)")
            out += [")", ""]

    for demand in demands:
        slot = bindings.binding_for(demand.lifecycle.slot.request_id)
        lifecycle = encoded[demand.name]
        if demand.invalidation is not None:
            out += [
                f"; Invalidation: {demand.name} | ACTIVE / ISSUED / PENDING -> CANCELLED",
                "(defrule",
                "    (or",
                f"        (goal demand-{demand.name} {lifecycle.active.value})",
                "        (or",
                f"            (goal demand-{demand.name} {lifecycle.issued.value})",
                f"            (goal demand-{demand.name} {lifecycle.pending.value})",
                "        )",
                "    )",
                f"    {demand.invalidation.expression.source}",
                "=>",
                f"    (set-goal demand-{demand.name} {lifecycle.cancelled.value})",
                ")",
                "",
            ]

        out += [
            f"; Pending diagnostics: {demand.name}",
        ]
        for diagnostic in demand.pending_diagnostics:
            message = diagnostic.message.format(
                active_goal=slot.id.value,
                pending_goal=lifecycle.pending.value,
                completed_goal=lifecycle.complete.value,
            )
            out.append(
                f"; PENDING-DIAGNOSTIC [{diagnostic.severity}] "
                f"{diagnostic.code}: {message}"
            )

        out += [
            f"; Issuance failure: {demand.name} | RETAIN-ACTIVE",
            f"; An unsatisfied issuance guard leaves demand-{demand.name} in ACTIVE; it is not PENDING.",
            f"; Release: {demand.name} | COMPLETE -> RELEASED",
            "(defrule",
            f"    (goal demand-{demand.name} {lifecycle.complete.value})",
            f"    {demand.release.source}",
            "=>",
            f"    (set-goal demand-{demand.name} {lifecycle.released.value})",
            ")",
            "",
        ]

        construction = demand.construction_lifecycle
        if construction is not None:
            out += [
                f"; Construction observation: {demand.name}",
                "; Precedence: COMPLETE > FOUNDATION_PENDING > PLACEMENT_PENDING > RETRY",
                f"; Completion witness: {demand.name} | PENDING/ISSUED -> COMPLETE",
            ]
            for transition in construction_transition_rules():
                if transition.kind is ConstructionTransitionKind.COMPLETE:
                    label = "; COMPLETE | ISSUED/PENDING -> COMPLETE"
                    guards = [
                        "    (or",
                        f"        (goal demand-{demand.name} {lifecycle.issued.value})",
                        f"        (goal demand-{demand.name} {lifecycle.pending.value})",
                        "    )",
                        f"    {demand.witness.source}",
                    ]
                    actions = [
                        f"    (set-goal demand-{demand.name} {lifecycle.complete.value})",
                    ]
                elif transition.kind is ConstructionTransitionKind.FOUNDATION_PENDING:
                    label = f"; Pending admission: {demand.name} | ISSUED/PENDING -> PENDING"
                    guards = [
                        "    (or",
                        f"        (goal demand-{demand.name} {lifecycle.issued.value})",
                        f"        (goal demand-{demand.name} {lifecycle.pending.value})",
                        "    )",
                        f"    (not {demand.witness.source})",
                        f"    {construction.pending_foundation_fact.source}",
                    ]
                    actions = [
                        f"    (set-goal demand-{demand.name} {lifecycle.pending.value})",
                    ]
                elif transition.kind is ConstructionTransitionKind.PLACEMENT_PENDING:
                    label = f"; PLACEMENT_PENDING | ISSUED/PENDING -> PENDING"
                    guards = [
                        "    (or",
                        f"        (goal demand-{demand.name} {lifecycle.issued.value})",
                        f"        (goal demand-{demand.name} {lifecycle.pending.value})",
                        "    )",
                        f"    (not {demand.witness.source})",
                        f"    (up-pending-objects c: {construction.native_building_id} == 0)",
                        f"    {construction.pending_placement_fact.source}",
                    ]
                    actions = [
                        f"    (set-goal demand-{demand.name} {lifecycle.pending.value})",
                    ]
                else:
                    label = "; RETRY | ISSUED/PENDING -> ACTIVE"
                    guards = [
                        "    (or",
                        f"        (goal demand-{demand.name} {lifecycle.issued.value})",
                        f"        (goal demand-{demand.name} {lifecycle.pending.value})",
                        "    )",
                        f"    (not {demand.witness.source})",
                        f"    (up-pending-objects c: {construction.native_building_id} == 0)",
                        f"    (not {construction.pending_placement_fact.source})",
                    ]
                    actions = [
                        f"    (set-goal demand-{demand.name} {lifecycle.active.value})",
                    ]
                    if demand.construction_retry_barrier is None:
                        raise CompileError(
                            f"CONSTRUCTION-BARRIER-MISSING: construction demand '{demand.name}' "
                            "has no retry barrier storage"
                        )
                    actions.append(
                        f"    (set-goal construction-retry-barrier-{demand.name} 1)"
                    )
                out += [label, "(defrule", *guards, "=>", *actions, ")", ""]
        else:
            out += [
                f"; Completion witness: {demand.name} | PENDING -> COMPLETE",
                "(defrule",
                f"    (goal demand-{demand.name} {lifecycle.pending.value})",
                f"    {demand.witness.source}",
                "=>",
                f"    (set-goal demand-{demand.name} {lifecycle.complete.value})",
                ")",
                "",
                f"; Pending admission: {demand.name} | ISSUED -> PENDING",
                "(defrule",
                f"    (goal demand-{demand.name} {lifecycle.issued.value})",
                "=>",
                f"    (set-goal demand-{demand.name} {lifecycle.pending.value})",
                ")",
                "",
            ]

        out += [
            f"; Action issuance: {demand.name} | ACTIVE -> ISSUED",
            "(defrule",
            f"    (goal demand-{demand.name} {lifecycle.active.value})",
            f"    (not {demand.witness.source})",
        ]

        if construction is not None:
            out += [
                f"    (goal construction-retry-barrier-{demand.name} 0)",
                f"    (up-pending-objects c: {construction.native_building_id} == 0)",
                f"    (not {construction.pending_placement_fact.source})",
            ]

        out += [
            f"    (not {demand.release.source})",
        ]

        request = demand.action.arbitration_request
        if request is not None:
            conflict_class = request.request_id.purpose.split(":", 1)[1]
            out.append(f"    (goal {_claim_name(conflict_class)} 0)")

        out.extend(
            f"    {requirement.expression.source}"
            for requirement in demand.requirements
        )
        out += [
            "=>",
            f"    {demand.action.expression.source}",
        ]

        if request is not None:
            conflict_class = request.request_id.purpose.split(":", 1)[1]
            out.append(f"    (set-goal {_claim_name(conflict_class)} 1)")

        out += [
            f"    (set-goal demand-{demand.name} {lifecycle.issued.value})",
            ")",
            "",
        ]

    result = "\n".join(out).rstrip() + "\n"
    _validate_artifact_budget(result)
    return result
