"""Deterministic semantic IR -> AoE2 .per emitter."""
from __future__ import annotations

from ..errors import CompileError
from ..ir import NativeControlPlan, SemanticDemand
from ..primitives import PrimitiveRegistry, default_de_registry
from ..runtime_binding import (
    BindingResult,
    GoalSlot,
    LifecycleEncoding,
    StrategicNumberSlot,
    TimerSlot,
)
from ..semantic.native_control import validate_native_control_plan

MAX_RULES = 10_000
MAX_RULE_ELEMENTS = 32
MAX_LINE_LENGTH = 255
INITIALIZATION_CHUNK = 30


def _claim_name(conflict_class: str) -> str:
    return "action-claim-" + conflict_class.lower().replace("_", "-")


def _extract_rules(text: str) -> list[str]:
    rules = []
    cursor = 0
    while True:
        start = text.find("(defrule", cursor)
        if start < 0:
            return rules
        depth = 0
        end = None
        for index in range(start, len(text)):
            char = text[index]
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
                if depth == 0:
                    end = index + 1
                    break
        if end is None:
            raise CompileError("EMITTER-UNBALANCED-RULE: generated rule is not closed")
        rules.append(text[start:end])
        cursor = end


def _validate_artifact_budget(text: str) -> None:
    rules = _extract_rules(text)
    if len(rules) > MAX_RULES:
        raise CompileError(
            f"EMITTER-RULE-LIMIT: generated artifact has {len(rules)} rules; "
            f"DE limit is {MAX_RULES}"
        )
    longest_line = max((len(line) for line in text.splitlines()), default=0)
    if longest_line > MAX_LINE_LENGTH:
        raise CompileError(
            f"EMITTER-LINE-LIMIT: generated line has {longest_line} characters; "
            f"DE limit is {MAX_LINE_LENGTH}"
        )
    for index, rule in enumerate(rules, 1):
        elements = rule.count("(") - 1
        if elements > MAX_RULE_ELEMENTS:
            raise CompileError(
                f"EMITTER-RULE-ELEMENT-LIMIT: generated rule {index} has "
                f"{elements} elements; DE limit is {MAX_RULE_ELEMENTS}"
            )


def emit(
    demands: list[SemanticDemand],
    bindings: BindingResult,
    compiler_version: str = "0.4",
    *,
    registry: PrimitiveRegistry | None = None,
    control_plan: NativeControlPlan | None = None,
) -> str:
    registry = registry or default_de_registry()
    if control_plan is not None:
        validate_native_control_plan(control_plan, registry)
    out = [
        ";============================================================",
        "; AOE2 .PER GENERATED BY COMPILER",
        f"; Compiler: AoE2 .per Compiler {compiler_version}",
        "; Generated from validated semantic IR. Do not edit by hand.",
        ";============================================================",
        "",
        "; Demand goal constants",
    ]

    encoded: dict[str, LifecycleEncoding] = {}
    arbitration_requests = {}
    for demand in demands:
        slot = bindings.binding_for(demand.lifecycle.slot.request_id)
        lifecycle = encoded[demand.name]
        if demand.invalidation is not None:
            out += [
                f"; Invalidation: {demand.name} | ACTIVE / ISSUED / PENDING -> CANCELLED",
                "(defrule",
                "    (or",
                f"        (goal demand-{demand.name} {lifecycle.active.value})",
                "        (or",
                f"            (goal demand-{demand.name} {lifecycle.issued.value})",
                f"            (goal demand-{demand.name} {lifecycle.pending.value})",
                "        )",
                "    )",
                f"    {demand.invalidation.expression.source}",
                "=>",
                f"    (set-goal demand-{demand.name} {lifecycle.cancelled.value})",
                ")",
                "",
            ]

        out += [
            f"; Pending diagnostics: {demand.name}",
        ]
        for diagnostic in demand.pending_diagnostics:
            message = diagnostic.message.format(
                active_goal=slot.id.value,
                pending_goal=lifecycle.pending.value,
                completed_goal=lifecycle.complete.value,
            )
            out.append(
                f"; PENDING-DIAGNOSTIC [{diagnostic.severity}] "
                f"{diagnostic.code}: {message}"
            )

        out += [
            f"; Issuance failure: {demand.name} | RETAIN-ACTIVE",
            f"; An unsatisfied issuance guard leaves demand-{demand.name} in ACTIVE; it is not PENDING.",
            f"; Release: {demand.name} | COMPLETE -> RELEASED",
            "(defrule",
            f"    (goal demand-{demand.name} {lifecycle.complete.value})",
            f"    {demand.release.source}",
            "=>",
            f"    (set-goal demand-{demand.name} {lifecycle.released.value})",
            ")",
            "",
        ]

        construction = demand.construction_lifecycle
        if construction is not None:
            out += [
                f"; Construction observation: {demand.name}",
                "; Precedence: COMPLETE > FOUNDATION_PENDING > PLACEMENT_PENDING > RETRY",
                f"; COMPLETE | ISSUED/PENDING -> COMPLETE",
                "(defrule",
                "    (or",
                f"        (goal demand-{demand.name} {lifecycle.issued.value})",
                f"        (goal demand-{demand.name} {lifecycle.pending.value})",
                "    )",
                f"    {demand.witness.source}",
                "=>",
                f"    (set-goal demand-{demand.name} {lifecycle.complete.value})",
                ")",
                "",
                f"; FOUNDATION_PENDING | ISSUED/PENDING -> PENDING",
                "(defrule",
                "    (or",
                f"        (goal demand-{demand.name} {lifecycle.issued.value})",
                f"        (goal demand-{demand.name} {lifecycle.pending.value})",
                "    )",
                f"    (not {demand.witness.source})",
                f"    {construction.pending_foundation_fact.source}",
                "=>",
                f"    (set-goal demand-{demand.name} {lifecycle.pending.value})",
                ")",
                "",
                f"; PLACEMENT_PENDING | ISSUED/PENDING -> PENDING",
                "(defrule",
                "    (or",
                f"        (goal demand-{demand.name} {lifecycle.issued.value})",
                f"        (goal demand-{demand.name} {lifecycle.pending.value})",
                "    )",
                f"    (not {demand.witness.source})",
                f"    (up-pending-objects c: {construction.building} == 0)",
                f"    {construction.pending_placement_fact.source}",
                "=>",
                f"    (set-goal demand-{demand.name} {lifecycle.pending.value})",
                ")",
                "",
                f"; RETRY | ISSUED/PENDING -> ACTIVE",
                "(defrule",
                "    (or",
                f"        (goal demand-{demand.name} {lifecycle.issued.value})",
                f"        (goal demand-{demand.name} {lifecycle.pending.value})",
                "    )",
                f"    (not {demand.witness.source})",
                f"    (up-pending-objects c: {construction.building} == 0)",
                f"    (not {construction.pending_placement_fact.source})",
                "=>",
                f"    (set-goal demand-{demand.name} {lifecycle.active.value})",
                ")",
                "",
            ]
        else:
            out += [
                f"; Completion witness: {demand.name} | PENDING -> COMPLETE",
                "(defrule",
                f"    (goal demand-{demand.name} {lifecycle.pending.value})",
                f"    {demand.witness.source}",
                "=>",
                f"    (set-goal demand-{demand.name} {lifecycle.complete.value})",
                ")",
                "",
                f"; Pending admission: {demand.name} | ISSUED -> PENDING",
                "(defrule",
                f"    (goal demand-{demand.name} {lifecycle.issued.value})",
                "=>",
                f"    (set-goal demand-{demand.name} {lifecycle.pending.value})",
                ")",
                "",
            ]

        out += [
            f"; Action issuance: {demand.name} | ACTIVE -> ISSUED",
            "(defrule",
            f"    (goal demand-{demand.name} {lifecycle.active.value})",
            f"    (not {demand.witness.source})",
        ]

        if construction is not None:
            out += [
                f"    {construction.pending_foundation_fact.source.replace('>= 1', '== 0')}",
                f"    (not {construction.pending_placement_fact.source})",
            ]

        out += [
            f"    (not {demand.release.source})",
        ]

        request = demand.action.arbitration_request
        if request is not None:
            conflict_class = request.request_id.purpose.split(":", 1)[1]
            out.append(f"    (goal {_claim_name(conflict_class)} 0)")

        out.extend(
            f"    {requirement.expression.source}"
            for requirement in demand.requirements
        )
        out += [
            "=>",
            f"    {demand.action.expression.source}",
        ]

        if request is not None:
            conflict_class = request.request_id.purpose.split(":", 1)[1]
            out.append(f"    (set-goal {_claim_name(conflict_class)} 1)")

        out += [
            f"    (set-goal demand-{demand.name} {lifecycle.issued.value})",
            ")",
            "",
        ]

    result = "\n".join(out).rstrip() + "\n"
    _validate_artifact_budget(result)
    return result
