"""Machine-checked Byzantine technology materialization seeds for Update 185872.

Each seed joins a manifest node to the pinned aoe2techtree technology snapshot by
TechId only after normalized names agree. The seeds intentionally carry no
prerequisite/provider/effect data beyond the manifest provider and age plus the
snapshot cost/research-time fields.
"""

from dataclasses import dataclass

from .game_data import Age, BuildingId, ResourceCost, TechId


@dataclass(frozen=True)
class ByzantineManifestTechnologySeed:
    id: TechId
    name: str
    available_age: Age
    provider_building: BuildingId
    snapshot_name: str
    base_cost: ResourceCost
    research_time_seconds: int

    def __post_init__(self) -> None:
        if not self.name.strip() or not self.snapshot_name.strip():
            raise ValueError("technology seed names must not be empty")
        if self.research_time_seconds < 0:
            raise ValueError("technology seed research time must be non-negative")


BYZANTINE_MANIFEST_TECHNOLOGY_SEEDS = (
    ByzantineManifestTechnologySeed(
        TechId(211),
        "Padded Archer Armor",
        Age.FEUDAL,
        BuildingId(103),
        "Padded Archer Armor",
        ResourceCost(food=100, wood=0, gold=0, stone=0),
        40,
    ),
    ByzantineManifestTechnologySeed(
        TechId(212),
        "Leather Archer Armor",
        Age.CASTLE,
        BuildingId(103),
        "Leather Archer Armor",
        ResourceCost(food=150, wood=0, gold=150, stone=0),
        55,
    ),
    ByzantineManifestTechnologySeed(
        TechId(219),
        "Ring Archer Armor",
        Age.IMPERIAL,
        BuildingId(103),
        "Ring Archer Armor",
        ResourceCost(food=250, wood=0, gold=250, stone=0),
        70,
    ),
    ByzantineManifestTechnologySeed(
        TechId(199),
        "Fletching",
        Age.FEUDAL,
        BuildingId(103),
        "Fletching",
        ResourceCost(food=100, wood=0, gold=50, stone=0),
        30,
    ),
    ByzantineManifestTechnologySeed(
        TechId(200),
        "Bodkin Arrow",
        Age.CASTLE,
        BuildingId(103),
        "Bodkin Arrow",
        ResourceCost(food=200, wood=0, gold=100, stone=0),
        35,
    ),
    ByzantineManifestTechnologySeed(
        TechId(201),
        "Bracer",
        Age.IMPERIAL,
        BuildingId(103),
        "Bracer",
        ResourceCost(food=300, wood=0, gold=200, stone=0),
        40,
    ),
    ByzantineManifestTechnologySeed(
        TechId(67),
        "Forging",
        Age.FEUDAL,
        BuildingId(103),
        "Forging",
        ResourceCost(food=150, wood=0, gold=0, stone=0),
        50,
    ),
    ByzantineManifestTechnologySeed(
        TechId(68),
        "Iron Casting",
        Age.CASTLE,
        BuildingId(103),
        "Iron casting",
        ResourceCost(food=220, wood=0, gold=120, stone=0),
        75,
    ),
    ByzantineManifestTechnologySeed(
        TechId(81),
        "Scale Barding Armor",
        Age.FEUDAL,
        BuildingId(103),
        "Scale Barding Armor",
        ResourceCost(food=150, wood=0, gold=0, stone=0),
        45,
    ),
    ByzantineManifestTechnologySeed(
        TechId(82),
        "Chain Barding Armor",
        Age.CASTLE,
        BuildingId(103),
        "Chain Barding Armor",
        ResourceCost(food=250, wood=0, gold=150, stone=0),
        60,
    ),
    ByzantineManifestTechnologySeed(
        TechId(80),
        "Plate Barding Armor",
        Age.IMPERIAL,
        BuildingId(103),
        "Plate Barding Armor",
        ResourceCost(food=350, wood=0, gold=200, stone=0),
        75,
    ),
    ByzantineManifestTechnologySeed(
        TechId(74),
        "Scale Mail Armor",
        Age.FEUDAL,
        BuildingId(103),
        "Scale Mail Armor",
        ResourceCost(food=100, wood=0, gold=0, stone=0),
        40,
    ),
    ByzantineManifestTechnologySeed(
        TechId(76),
        "Chain Mail Armor",
        Age.CASTLE,
        BuildingId(103),
        "Chain Mail Armor",
        ResourceCost(food=200, wood=0, gold=100, stone=0),
        55,
    ),
    ByzantineManifestTechnologySeed(
        TechId(77),
        "Plate Mail Armor",
        Age.IMPERIAL,
        BuildingId(103),
        "Plate Mail Armor",
        ResourceCost(food=300, wood=0, gold=150, stone=0),
        70,
    ),
    ByzantineManifestTechnologySeed(
        TechId(194),
        "Fortified Wall",
        Age.CASTLE,
        BuildingId(209),
        "Fortified Wall",
        ResourceCost(food=200, wood=100, gold=0, stone=0),
        50,
    ),
    ByzantineManifestTechnologySeed(
        TechId(64),
        "Bombard Tower",
        Age.IMPERIAL,
        BuildingId(209),
        "Bombard Tower",
        ResourceCost(food=800, wood=400, gold=0, stone=0),
        60,
    ),
    ByzantineManifestTechnologySeed(
        TechId(140),
        "Guard Tower",
        Age.CASTLE,
        BuildingId(209),
        "Guard Tower",
        ResourceCost(food=100, wood=250, gold=0, stone=0),
        30,
    ),
    ByzantineManifestTechnologySeed(
        TechId(63),
        "Keep",
        Age.IMPERIAL,
        BuildingId(209),
        "Keep",
        ResourceCost(food=500, wood=350, gold=0, stone=0),
        75,
    ),
    ByzantineManifestTechnologySeed(
        TechId(608),
        "Arrowslits",
        Age.IMPERIAL,
        BuildingId(209),
        "Arrowslits",
        ResourceCost(food=250, wood=250, gold=0, stone=0),
        25,
    ),
    ByzantineManifestTechnologySeed(
        TechId(322),
        "Murder Holes",
        Age.CASTLE,
        BuildingId(209),
        "Murder Holes",
        ResourceCost(food=200, wood=0, gold=0, stone=100),
        35,
    ),
    ByzantineManifestTechnologySeed(
        TechId(908),
        "Clinker Construction",
        Age.CASTLE,
        BuildingId(209),
        "Clinker Construction",
        ResourceCost(food=150, wood=100, gold=0, stone=0),
        50,
    ),
    ByzantineManifestTechnologySeed(
        TechId(907),
        "Carvel Hull",
        Age.IMPERIAL,
        BuildingId(209),
        "Carvel Hull",
        ResourceCost(food=350, wood=200, gold=0, stone=0),
        60,
    ),
    ByzantineManifestTechnologySeed(
        TechId(379),
        "Hoardings",
        Age.IMPERIAL,
        BuildingId(82),
        "Hoardings",
        ResourceCost(food=400, wood=400, gold=0, stone=0),
        75,
    ),
    ByzantineManifestTechnologySeed(
        TechId(315),
        "Conscription",
        Age.IMPERIAL,
        BuildingId(82),
        "Conscription",
        ResourceCost(food=150, wood=0, gold=150, stone=0),
        60,
    ),
    ByzantineManifestTechnologySeed(
        TechId(46),
        "Devotion",
        Age.CASTLE,
        BuildingId(104),
        "Devotion",
        ResourceCost(food=100, wood=0, gold=200, stone=0),
        40,
    ),
    ByzantineManifestTechnologySeed(
        TechId(45),
        "Faith",
        Age.IMPERIAL,
        BuildingId(104),
        "Faith",
        ResourceCost(food=550, wood=0, gold=750, stone=0),
        60,
    ),
    ByzantineManifestTechnologySeed(
        TechId(316),
        "Redemption",
        Age.CASTLE,
        BuildingId(104),
        "Redemption",
        ResourceCost(food=0, wood=0, gold=475, stone=0),
        50,
    ),
    ByzantineManifestTechnologySeed(
        TechId(233),
        "Illumination",
        Age.IMPERIAL,
        BuildingId(104),
        "Illumination",
        ResourceCost(food=0, wood=0, gold=120, stone=0),
        65,
    ),
    ByzantineManifestTechnologySeed(
        TechId(319),
        "Atonement",
        Age.CASTLE,
        BuildingId(104),
        "Atonement",
        ResourceCost(food=0, wood=0, gold=325, stone=0),
        40,
    ),
    ByzantineManifestTechnologySeed(
        TechId(230),
        "Block Printing",
        Age.IMPERIAL,
        BuildingId(104),
        "Block Printing",
        ResourceCost(food=0, wood=0, gold=200, stone=0),
        55,
    ),
    ByzantineManifestTechnologySeed(
        TechId(438),
        "Theocracy",
        Age.IMPERIAL,
        BuildingId(104),
        "Theocracy",
        ResourceCost(food=0, wood=0, gold=200, stone=0),
        75,
    ),
    ByzantineManifestTechnologySeed(
        TechId(439),
        "Heresy",
        Age.CASTLE,
        BuildingId(104),
        "Heresy",
        ResourceCost(food=0, wood=0, gold=1000, stone=0),
        60,
    ),
    ByzantineManifestTechnologySeed(
        TechId(231),
        "Sanctity",
        Age.CASTLE,
        BuildingId(104),
        "Sanctity",
        ResourceCost(food=0, wood=0, gold=175, stone=0),
        60,
    ),
    ByzantineManifestTechnologySeed(
        TechId(252),
        "Fervor",
        Age.CASTLE,
        BuildingId(104),
        "Fervor",
        ResourceCost(food=0, wood=0, gold=140, stone=0),
        50,
    ),
    ByzantineManifestTechnologySeed(
        TechId(22),
        "Loom",
        Age.DARK,
        BuildingId(109),
        "Loom",
        ResourceCost(food=0, wood=0, gold=50, stone=0),
        25,
    ),
    ByzantineManifestTechnologySeed(
        TechId(213),
        "Wheelbarrow",
        Age.FEUDAL,
        BuildingId(109),
        "Wheel Barrow",
        ResourceCost(food=175, wood=50, gold=0, stone=0),
        75,
    ),
    ByzantineManifestTechnologySeed(
        TechId(249),
        "Hand Cart",
        Age.CASTLE,
        BuildingId(109),
        "Hand Cart",
        ResourceCost(food=300, wood=200, gold=0, stone=0),
        55,
    ),
    ByzantineManifestTechnologySeed(
        TechId(55),
        "Gold Mining",
        Age.FEUDAL,
        BuildingId(584),
        "Gold Mining",
        ResourceCost(food=100, wood=75, gold=0, stone=0),
        30,
    ),
    ByzantineManifestTechnologySeed(
        TechId(182),
        "Gold Shaft Mining",
        Age.CASTLE,
        BuildingId(584),
        "Gold Shaft Mining",
        ResourceCost(food=175, wood=75, gold=0, stone=0),
        75,
    ),
    ByzantineManifestTechnologySeed(
        TechId(278),
        "Stone Mining",
        Age.FEUDAL,
        BuildingId(584),
        "Stone Mining",
        ResourceCost(food=100, wood=75, gold=0, stone=0),
        30,
    ),
    ByzantineManifestTechnologySeed(
        TechId(279),
        "Stone Shaft Mining",
        Age.CASTLE,
        BuildingId(584),
        "Stone Shaft Mining",
        ResourceCost(food=175, wood=75, gold=0, stone=0),
        75,
    ),
    ByzantineManifestTechnologySeed(
        TechId(202),
        "Double-Bit Axe",
        Age.FEUDAL,
        BuildingId(562),
        "Double Bit Axe",
        ResourceCost(food=100, wood=50, gold=0, stone=0),
        25,
    ),
    ByzantineManifestTechnologySeed(
        TechId(203),
        "Bow Saw",
        Age.CASTLE,
        BuildingId(562),
        "Bow Saw",
        ResourceCost(food=150, wood=100, gold=0, stone=0),
        50,
    ),
    ByzantineManifestTechnologySeed(
        TechId(221),
        "Two-Man Saw",
        Age.IMPERIAL,
        BuildingId(562),
        "Two Man Saw",
        ResourceCost(food=300, wood=200, gold=0, stone=0),
        100,
    ),
    ByzantineManifestTechnologySeed(
        TechId(48),
        "Caravan",
        Age.CASTLE,
        BuildingId(84),
        "Caravan",
        ResourceCost(food=200, wood=0, gold=200, stone=0),
        40,
    ),
    ByzantineManifestTechnologySeed(
        TechId(23),
        "Coinage",
        Age.CASTLE,
        BuildingId(84),
        "Coinage",
        ResourceCost(food=200, wood=0, gold=100, stone=0),
        70,
    ),
    ByzantineManifestTechnologySeed(
        TechId(17),
        "Banking",
        Age.IMPERIAL,
        BuildingId(84),
        "Banking",
        ResourceCost(food=300, wood=0, gold=200, stone=0),
        70,
    ),
    ByzantineManifestTechnologySeed(
        TechId(15),
        "Guilds",
        Age.IMPERIAL,
        BuildingId(84),
        "Guilds",
        ResourceCost(food=300, wood=0, gold=200, stone=0),
        50,
    ),
    ByzantineManifestTechnologySeed(
        TechId(14),
        "Horse Collar",
        Age.FEUDAL,
        BuildingId(68),
        "Horse collar",
        ResourceCost(food=75, wood=75, gold=0, stone=0),
        20,
    ),
    ByzantineManifestTechnologySeed(
        TechId(13),
        "Heavy Plow",
        Age.CASTLE,
        BuildingId(68),
        "Heavy plow",
        ResourceCost(food=125, wood=125, gold=0, stone=0),
        40,
    ),
    ByzantineManifestTechnologySeed(
        TechId(12),
        "Crop Rotation",
        Age.IMPERIAL,
        BuildingId(68),
        "Crop rotation",
        ResourceCost(food=250, wood=250, gold=0, stone=0),
        70,
    ),
)

__all__ = ["BYZANTINE_MANIFEST_TECHNOLOGY_SEEDS", "ByzantineManifestTechnologySeed"]
